name:                agreeing
version:             0.2.1.0
github:              "jcranch/agreement"
license:             BSD3
author:              "James Cranch"
maintainer:          "j.d.cranch@sheffield.ac.uk"
copyright:           "2023 James Cranch"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Idiomatic data structure for agreement
category:            Data
description:         Please see the README on GitHub at <https://github.com/jcranch/agreeing#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  agreeing-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agreeing
    - hspec              >= 2.7     && < 2.12
